language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - extra-google-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
jdk:
  - oraclejdk8
